### ISSUE TITLE
Doesn't display apps in ComputerCraft 1.75 and 1.79

### ISSUE THREAD

**Issue by FuzzyLitchi** [SertexTeam/sPhone#13]
I haven't tried other versions but i can't access any apps.

[Here](https://gfycat.com/GreatPerfumedCanadagoose) is how to reproduce.

**Comment by Ale32bit** [comment]
Thanks for the report. I already know this bug, but, since I don't have much time plus I'm recoding all the code, I might not fix it.

Thanks anyway.

**Comment by FuzzyLitchi** [comment]
Okay, Thanks for answering.

**Comment by Ale32bit** [comment]
Hi @FuzzyLitchi , it's been 10 months and I'm happy to announce sPhone 2 is in development here https://github.com/Ale32bit/sPhone-2
Hopefully the bug isn't there.
