### ISSUE TITLE
Publish source of backend

### ISSUE THREAD

**Issue by ThePhoenix47** [SertexTeam/sPhone#14]
I'm sorry to be bothering you again, but now that the backend is down anyway, is there any good reason not to publish it? It's not like there is any good reason to keep it secret, and that way, you would at least give people a chance to still use your software.

**Comment by Ale32bit** [comment]
Backend of what?

**Comment by ThePhoenix47** [comment]
The server that runs your "SertexID" things.

**Comment by Ale32bit** [comment]
Why do you guys really want that code?

**Comment by ThePhoenix47** [comment]
Curiosity, mainly. The fact that you are withholding it just makes us even more interested what's really in there.

**Comment by Ale32bit** [comment]
I lost the code anyway.

**Comment by TheMrIron2** [comment]
In Phoenix's defense, making the backend open source would allow the project to be kept alive by the community forever - keeping it closed means it's lost forever once you shut it down

**Comment by ThePhoenix47** [comment]
Well, that's a pity. I would comment on how that wouldn't have happened if it had been on GitHub in the first place, but that doesn't really seem to be helpful. Also, that means this is obsolete.

**Comment by Ale32bit** [comment]
I had that code in an old drive, time ago. It had nothing special anyway, just PHP and MySQL

**Comment by Ale32bit** [comment]
If I remember correctly, there were 2 tables in a db: accounts and messages.

**Comment by ThePhoenix47** [comment]
That was what it looked like, but it still would've been interesting. Leaves the question why you never published it, but then again, I suppose it doesn't matter in the end.

**Comment by Ale32bit** [comment]
I'm not proud of that code, I hate it.
A "friend" made it, but that's another story which I prefer to not say.

**Comment by ThePhoenix47** [comment]
Don't, then - it's not like I care.

**Comment by Ale32bit** [comment]
Thanks anyway for asking. I lost faith on sPhone.

Locking issue
